// examples/cool-store-angular/src/app/components/todo-form/todo-form.component.ts
import { Component, OnInit } from "@angular/core";
import { FormGroup, FormControl, Validators } from "@angular/forms";
import { TodosService } from "src/app/services/todos.service";

@Component({
  selector: "app-todo-form",
  templateUrl: "./todo-form.component.html",
  styleUrls: ["./todo-form.component.scss"]
})
export class TodoFormComponent implements OnInit {
  todoForm: FormGroup;

  constructor(private todosService: TodosService) {}

  ngOnInit() {
    this.todoForm = new FormGroup({
      name: new FormControl(null, Validators.required)
    });
  }

  onSubmit() {
    const { valid, value } = this.todoForm;

    if (valid) {
      this.todosService.addTodo(value);
      this.todoForm.reset();
    } else {
      alert("Please enter a toto!");
    }
  }
}

<form [formGroup]="todoForm" (ngSubmit)="onSubmit()">
  <input
    formControlName="name"
    type="text"
    class="form-control"
    placeholder="Please enter a Todo name!"
  />
</form>

// examples/with-react/src/components/TodoForm.tsx
import React, { useState, FormEvent } from "react";

import { Todo } from "../interfaces/todo";
import { addTodo } from "../services/todosService";

export function TodoForm() {
  const [todo, setTodo] = useState<Todo>({ name: "" });

  function onSubmit(event: FormEvent) {
    event.preventDefault();
    addTodo(todo);
    setTodo({ name: "" });
  }

  return (
    <form onSubmit={onSubmit}>
      <input
        type="text"
        value={todo.name}
        onChange={event => setTodo({ ...todo, name: event.target.value })}
        className="form-control"
        placeholder="Please enter a Todo"
      />
    </form>
  );
}
